name: tests

trigger:
  branches:
    include:
      - '*'
pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_VERSION: '22.x'
  PNPM_VERSION: '8'   # adjust if you want a specific pnpm major version

jobs:
  - job: run_tests
    timeoutInMinutes: 15

    steps:
      - checkout: self
        displayName: 'Checkout repository'

      - task: NodeTool@0
        inputs:
          versionSpec: $(NODE_VERSION)
        displayName: 'Install Node.js $(NODE_VERSION)'

      - script: |
          npm i -g pnpm@$(PNPM_VERSION)
          pnpm --version
        displayName: 'Install PNPM'

      - task: Cache@2
        inputs:
          key: 'pnpm | "$(Agent.OS)" | pnpm-lock.yaml'
          restoreKeys: |
            pnpm | "$(Agent.OS)"
          path: |
            ~/.pnpm-store
            node_modules/.pnpm
        displayName: 'Cache pnpm store & pnpm modules'

      - script: |
          pnpm install
        displayName: 'Install dependencies (pnpm)'

      - script: |
          set -x
          pnpm run typecheck
        displayName: 'TypeScript check'

      - script: |
          set -x
          pnpm run test:ci
        displayName: 'Run tests with coverage'

      - script: |
          set -x
          pnpm run lint:ci
        displayName: 'ESLint'

      - task: PublishCodeCoverageResults@2
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml
        condition: succeededOrFailed()
        displayName: 'Publish code coverage results'
