name: tests

trigger:
  branches:
    include:
      - '*'
pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_VERSION: '22.x'

jobs:
  - job: run_tests
    timeoutInMinutes: 15

    steps:
      - checkout: self
        displayName: 'Checkout Repository'

      - task: NodeTool@0
        inputs:
          versionSpec: $(NODE_VERSION)
        displayName: 'Install Node.js $(NODE_VERSION)'

      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false
        displayName: 'Setup PNPM'

      - task: Cache@2
        inputs:
          key: 'pnpm | "$(Agent.OS)" | pnpm-lock.yaml'
          restoreKeys: |
            pnpm | "$(Agent.OS)"
          path: ~/.pnpm-store
        displayName: 'Cache PNPM Store'

      - script: pnpm install --frozen-lockfile
        displayName: 'Install Dependencies'

      - script: pnpm run typecheck
        displayName: 'TypeScript Check'

      - script: pnpm run test:ci
        displayName: 'Run Tests with Coverage'

      - script: pnpm run lint:ci
        displayName: 'Lint Codebase'

      - task: PublishCodeCoverageResults@2
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml
        condition: succeededOrFailed()
        displayName: 'Publish Coverage Report'
