name: tests

trigger:
  branches:
    include:
      - '*'
pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Playwright E2E Tests
  - name: NODE_VERSION
    value: '22.x'
  - name: PNPM_VERSION
    value: '10.8.1'

jobs:
  - job: run_tests
    timeoutInMinutes: 20

    steps:
      - checkout: self
        displayName: 'Checkout repository'

      - task: NodeTool@0
        inputs:
          versionSpec: $(NODE_VERSION)
        displayName: 'Install Node.js $(NODE_VERSION)'

      - script: |
          npm i -g pnpm@$(PNPM_VERSION)
          pnpm --version
        displayName: 'Install PNPM'

      - script: |
          # Try to checkout the matching branch, if the command fails, don't care.
          export BRANCH_NAME=$(basename -- "$SYSTEM_PULLREQUEST_SOURCEBRANCH")
          export BRANCH_NAME=${BRANCH_NAME:-"$BUILD_SOURCEBRANCHNAME"}
          git checkout -b $BRANCH_NAME -t origin/$BRANCH_NAME || true
          pnpm install
        displayName: 'Install dependencies (pnpm)'

      - script: |
          set -xv  # Echo commands before they are run
          pnpm run typecheck
        displayName: 'TypeScript check'

      - script: |
          set -xv  # Echo commands before they are run
          pnpm run test:ci
        displayName: 'Run unit tests with coverage'

      - script: |
          set -xv  # Echo commands before they are run
          pnpm run lint:ci
        displayName: 'ESLint'

      # 🔹 Cache Playwright browsers
      - task: Cache@2
        inputs:
          key: 'playwright-browsers-$(Agent.OS)-$(NODE_VERSION)'
          path: $(HOME)/.cache/ms-playwright
        displayName: 'Cache Playwright browsers'

      - script: |
          npx playwright install --with-deps
        displayName: 'Install Playwright browsers'

      - script: |
          set -xv
          pnpm run e2e:ci
        displayName: 'Run Playwright E2E tests'

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: $(System.DefaultWorkingDirectory)/playwright-report
          artifactName: playwright-report
        condition: succeededOrFailed()
        displayName: 'Publish Playwright HTML report'

      - task: PublishCodeCoverageResults@2
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml
        condition: succeededOrFailed()
        displayName: 'Publish code coverage results'
