import type { FormHelperTextProps, IconButtonProps, TooltipProps, TypographyProps } from '@mui/material';
import type { useInputState } from 'components/visual/Inputs/components/InputComponents';
import type React from 'react';

export type InputProps<Type> = {
  defaultValue?: Type;
  disabled?: boolean;
  divider?: boolean;
  endAdornment?: React.ReactNode;
  error?: (value: Type) => string;
  errorProps?: FormHelperTextProps;
  expand?: boolean;
  expandProps?: IconButtonProps;
  helperText?: string;
  helperTextProps?: FormHelperTextProps;
  id?: string;
  indeterminate?: boolean;
  label?: string;
  labelProps?: TypographyProps;
  loading?: boolean;
  monospace?: boolean;
  password?: boolean;
  placeholder?: string;
  preventDisabledColor?: boolean;
  preventRender?: boolean;
  readOnly?: boolean;
  required?: boolean;
  reset?: boolean;
  resetProps?: IconButtonProps;
  rootProps?: React.HTMLAttributes<HTMLDivElement>;
  showOverflow?: boolean;
  startAdornment?: React.ReactNode;
  tiny?: boolean;
  tooltip?: TooltipProps['title'];
  tooltipProps?: Omit<TooltipProps, 'children' | 'title'>;
  value: Type;
  onBlur?: (event: React.SyntheticEvent | Event) => void;
  onChange?: (event: React.SyntheticEvent | Event, value: Type, ...other: unknown[]) => void;
  onError?: (error: string) => void;
  onExpand?: (event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void;
  onFocus?: (event: React.SyntheticEvent | Event) => void;
  onReset?: IconButtonProps['onClick'];
};

export type InputState<Type, P> = ReturnType<typeof useInputState<Type, P>>;
